#!/bin/sh
#Automation - It contains command to install the ZUG 
#Author:Sankha Sil
# ©Copyright 2009 Automature Inc.. All Rights Reserved.

#invoking Setup
sudo ./setup
#cleanup
#sudo rm -r *
#Comments after Install
echo "Please verify the installation with runzug -v"