package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	int applicationId;
	String applicationName;
	String applicationVersion;
	String settings;
	String applicationDesc;
	Set<Applicationlist> applicationlists = new HashSet<Applicationlist> (0);

	public Application() {
	}

	public Application(int applicationId, String applicationName,
			String applicationVersion) {
		this.applicationId = applicationId;
		this.applicationName = applicationName;
		this.applicationVersion = applicationVersion;
	}

	public Application(int applicationId, String applicationName,
			String applicationVersion, String settings, String applicationDesc,
			Set<Applicationlist> applicationlists) {
		this.applicationId = applicationId;
		this.applicationName = applicationName;
		this.applicationVersion = applicationVersion;
		this.settings = settings;
		this.applicationDesc = applicationDesc;
		this.applicationlists = applicationlists;
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	public String getApplicationVersion() {
		return this.applicationVersion;
	}

	public void setApplicationVersion(String applicationVersion) {
		this.applicationVersion = applicationVersion;
	}

	public String getSettings() {
		return this.settings;
	}

	public void setSettings(String settings) {
		this.settings = settings;
	}

	public String getApplicationDesc() {
		return this.applicationDesc;
	}

	public void setApplicationDesc(String applicationDesc) {
		this.applicationDesc = applicationDesc;
	}

	public Set<Applicationlist> getApplicationlists() {
		return this.applicationlists;
	}

	public void setApplicationlists(Set<Applicationlist> applicationlists) {
		this.applicationlists = applicationlists;
	}

}
