package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Auditlog generated by hbm2java
 */
@SuppressWarnings("serial")
public class Auditlog implements java.io.Serializable {

	private int auditLogId;
	private Date entryDateTime;
	private String userName;
	private String tableName;
	private String operationType;
	private String logEntry;

	public Auditlog() {
	}

	public Auditlog(int auditLogId, Date entryDateTime, String userName,
			String tableName, String operationType, String logEntry) {
		this.auditLogId = auditLogId;
		this.entryDateTime = entryDateTime;
		this.userName = userName;
		this.tableName = tableName;
		this.operationType = operationType;
		this.logEntry = logEntry;
	}

	public int getAuditLogId() {
		return this.auditLogId;
	}

	public void setAuditLogId(int auditLogId) {
		this.auditLogId = auditLogId;
	}

	public Date getEntryDateTime() {
		return this.entryDateTime;
	}

	public void setEntryDateTime(Date entryDateTime) {
		this.entryDateTime = entryDateTime;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getOperationType() {
		return this.operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	public String getLogEntry() {
		return this.logEntry;
	}

	public void setLogEntry(String logEntry) {
		this.logEntry = logEntry;
	}

}
