package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * CounterId generated by hbm2java
 */
@SuppressWarnings("serial")
public class CounterId implements java.io.Serializable {

	private String tableName;
	private String value;
	private Long sequence;
	private String prefix;

	public CounterId() {
	}

	public CounterId(String tableName, String value) {
		this.tableName = tableName;
		this.value = value;
	}

	public CounterId(String tableName, String value, Long sequence,
			String prefix) {
		this.tableName = tableName;
		this.value = value;
		this.sequence = sequence;
		this.prefix = prefix;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Long getSequence() {
		return this.sequence;
	}

	public void setSequence(Long sequence) {
		this.sequence = sequence;
	}

	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CounterId))
			return false;
		CounterId castOther = (CounterId) other;

		return ((this.getTableName() == castOther.getTableName()) || (this
				.getTableName() != null
				&& castOther.getTableName() != null && this.getTableName()
				.equals(castOther.getTableName())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null
						&& castOther.getValue() != null && this.getValue()
						.equals(castOther.getValue())))
				&& ((this.getSequence() == castOther.getSequence()) || (this
						.getSequence() != null
						&& castOther.getSequence() != null && this
						.getSequence().equals(castOther.getSequence())))
				&& ((this.getPrefix() == castOther.getPrefix()) || (this
						.getPrefix() != null
						&& castOther.getPrefix() != null && this.getPrefix()
						.equals(castOther.getPrefix())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result
				+ (getSequence() == null ? 0 : this.getSequence().hashCode());
		result = 37 * result
				+ (getPrefix() == null ? 0 : this.getPrefix().hashCode());
		return result;
	}

}
