package DatabaseLayer;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Frameworkmetadata generated by hbm2java
 */
@SuppressWarnings("serial")
public class Frameworkmetadata implements java.io.Serializable, IDataTable {

	Integer frameworkMetaDataId;
	String name;
	String value;

	public Frameworkmetadata() {
	}

	public Frameworkmetadata(int frameworkMetaDataId) {
		this.frameworkMetaDataId = frameworkMetaDataId;
	}

	public Frameworkmetadata(int frameworkMetaDataId, String name, String value) {
		this.frameworkMetaDataId = frameworkMetaDataId;
		this.name = name;
		this.value = value;
	}

	public Integer getFrameworkMetaDataId() {
		return this.frameworkMetaDataId;
	}

	public void setFrameworkMetaDataId(int frameworkMetaDataId) {
		this.frameworkMetaDataId = frameworkMetaDataId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null; 
		
		str="frameworkMetaData ID :"+getFrameworkMetaDataId();
		str+="\n";
		str+=" Name:"+getName();
		str+="\n";
		str+="value: "+getValue();
		str+="\n";
		
		Log.Debug("FrameworkMetaData:printString : + " + str);
		
		return str;
	}

}
