package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projectphase generated by hbm2java
 */
@SuppressWarnings("serial")
public class Projectphase implements java.io.Serializable {

	int projectPhaseId;
	Releases releases;
	String sprintName;
	Date startDate;
	Date endDate;
	Set<Testplan> testplans = new HashSet<Testplan> (0);
	Set<Build>  builds = new HashSet<Build> (0);

	public Projectphase() {
	}

	public Projectphase(int projectPhaseId, Releases releases) {
		this.projectPhaseId = projectPhaseId;
		this.releases = releases;
	}

	public Projectphase(int projectPhaseId, Releases releases,
			String sprintName, Date startDate, Date endDate, Set<Testplan> testplans,
			Set<Build> builds) {
		this.projectPhaseId = projectPhaseId;
		this.releases = releases;
		this.sprintName = sprintName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.testplans = testplans;
		this.builds = builds;
	}

	public int getProjectPhaseId() {
		return this.projectPhaseId;
	}

	public void setProjectPhaseId(int projectPhaseId) {
		this.projectPhaseId = projectPhaseId;
	}

	public Releases getReleases() {
		return this.releases;
	}

	public void setReleases(Releases releases) {
		this.releases = releases;
	}

	public String getSprintName() {
		return this.sprintName;
	}

	public void setSprintName(String sprintName) {
		this.sprintName = sprintName;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Set<Testplan> getTestplans() {
		return this.testplans;
	}

	public void setTestplans(Set<Testplan> testplans) {
		this.testplans = testplans;
	}

	public Set<Build> getBuilds() {
		return this.builds;
	}

	public void setBuilds(Set<Build> builds) {
		this.builds = builds;
	}

}
