package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Releases generated by hbm2java
 */
@SuppressWarnings("serial")
public class Releases implements java.io.Serializable, IDataTable {

	int releaseId;
	Product product;
	int majorVersion;
	Integer minorVersion;
	String description;
	Date conceivedDate;
	Date releasedDate;
	String codeName;
	Set<Requirements> requirementses = new HashSet<Requirements> (0);
	Set<Projectphase>  projectphases = new HashSet<Projectphase>  (0);

	public Releases() {
	}

	public Releases(int releaseId, Product product, int majorVersion,
			String codeName) {
		this.releaseId = releaseId;
		this.product = product;
		this.majorVersion = majorVersion;
		this.codeName = codeName;
	}

	public Releases(int releaseId, Product product, int majorVersion,
			Integer minorVersion, String description, Date conceivedDate,
			Date releasedDate, String codeName, Set<Requirements> requirementses,
			Set<Projectphase> projectphases) {
		this.releaseId = releaseId;
		this.product = product;
		this.majorVersion = majorVersion;
		this.minorVersion = minorVersion;
		this.description = description;
		this.conceivedDate = conceivedDate;
		this.releasedDate = releasedDate;
		this.codeName = codeName;
		this.requirementses = requirementses;
		this.projectphases = projectphases;
	}

	public int getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(int releaseId) {
		this.releaseId = releaseId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public int getMajorVersion() {
		return this.majorVersion;
	}

	public void setMajorVersion(int majorVersion) {
		this.majorVersion = majorVersion;
	}

	public Integer getMinorVersion() {
		return this.minorVersion;
	}

	public void setMinorVersion(Integer minorVersion) {
		this.minorVersion = minorVersion;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getConceivedDate() {
		return this.conceivedDate;
	}

	public void setConceivedDate(Date conceivedDate) {
		this.conceivedDate = conceivedDate;
	}

	public Date getReleasedDate() {
		return this.releasedDate;
	}

	public void setReleasedDate(Date releasedDate) {
		this.releasedDate = releasedDate;
	}

	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public Set<Requirements> getRequirementses() {
		return this.requirementses;
	}

	public void setRequirementses(Set<Requirements> requirementses) {
		this.requirementses = requirementses;
	}

	public Set<Projectphase> getProjectphases() {
		return this.projectphases;
	}

	public void setProjectphases(Set<Projectphase> projectphases) {
		this.projectphases = projectphases;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		
		
		str="ReleaseId: "+getReleaseId()+"\n";
		str+="Product ID:"+product.getProductId();
		str+="Major Version: "+getMajorVersion()+"\n";
		str+="Minor Version: "+getMinorVersion()+"\n";
		str+="Description: "+getDescription()+"\n";
		str+="Conceived Date: "+getConceivedDate()+"\n";
		str+="Code Name: "+getCodeName()+"\n";
		
		Log.Debug("Releases:printString : + " + str);
					
		return str;
	}

}
