package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Roleattributes generated by hbm2java
 */
@SuppressWarnings("serial")
public class Roleattributes implements java.io.Serializable {

	int roleAttributesId;
	Role role;
	String attributeName;
	byte optional;
	byte multiple;
	String roleName;

	public Roleattributes() {
	}

	public Roleattributes(int roleAttributesId, Role role,
			String attributeName, byte optional, byte multiple) {
		this.roleAttributesId = roleAttributesId;
		this.role = role;
		this.attributeName = attributeName;
		this.optional = optional;
		this.multiple = multiple;
	}

	public Roleattributes(int roleAttributesId, Role role,
			String attributeName, byte optional, byte multiple, String roleName) {
		this.roleAttributesId = roleAttributesId;
		this.role = role;
		this.attributeName = attributeName;
		this.optional = optional;
		this.multiple = multiple;
		this.roleName = roleName;
	}

	public int getRoleAttributesId() {
		return this.roleAttributesId;
	}

	public void setRoleAttributesId(int roleAttributesId) {
		this.roleAttributesId = roleAttributesId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public byte getOptional() {
		return this.optional;
	}

	public void setOptional(byte optional) {
		this.optional = optional;
	}

	public byte getMultiple() {
		return this.multiple;
	}

	public void setMultiple(byte multiple) {
		this.multiple = multiple;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
