package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * TagList generated by hbm2java
 */
@SuppressWarnings("serial")
public class TagList implements java.io.Serializable {

	int tagListId;
	String attribute;
	String value;

	public TagList() {
	}

	public TagList(int tagListId, String attribute, String value) {
		this.tagListId = tagListId;
		this.attribute = attribute;
		this.value = value;
	}

	public int getTagListId() {
		return this.tagListId;
	}

	public void setTagListId(int tagListId) {
		this.tagListId = tagListId;
	}

	public String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(String attribute) {
		this.attribute = attribute;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
