package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Testcycledetail generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testcycledetail implements java.io.Serializable {

	int testCycleDetailId;
	Testcycle testcycle;
	Topologyset topologyset;
	String roleName;
	String buildNo;

	public Testcycledetail() {
	}

	public Testcycledetail(int testCycleDetailId, Testcycle testcycle,
			Topologyset topologyset, String roleName) {
		this.testCycleDetailId = testCycleDetailId;
		this.testcycle = testcycle;
		this.topologyset = topologyset;
		this.roleName = roleName;
	}

	public Testcycledetail(int testCycleDetailId, Testcycle testcycle,
			Topologyset topologyset, String roleName, String buildNo) {
		this.testCycleDetailId = testCycleDetailId;
		this.testcycle = testcycle;
		this.topologyset = topologyset;
		this.roleName = roleName;
		this.buildNo = buildNo;
	}

	public int getTestCycleDetailId() {
		return this.testCycleDetailId;
	}

	public void setTestCycleDetailId(int testCycleDetailId) {
		this.testCycleDetailId = testCycleDetailId;
	}

	public Testcycle getTestcycle() {
		return this.testcycle;
	}

	public void setTestcycle(Testcycle testcycle) {
		this.testcycle = testcycle;
	}

	public Topologyset getTopologyset() {
		return this.topologyset;
	}

	public void setTopologyset(Topologyset topologyset) {
		this.topologyset = topologyset;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getBuildNo() {
		return this.buildNo;
	}

	public void setBuildNo(String buildNo) {
		this.buildNo = buildNo;
	}

}
