package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Testcaseignorelist generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testcaseignorelist implements java.io.Serializable {

	int testcaseignorelistId;
	Topology topology;
	Testsuite testsuite;
	Testcase testcase;
	String comment;

	public Testcaseignorelist() {
	}

	public Testcaseignorelist(int testcaseignorelistId) {
		this.testcaseignorelistId = testcaseignorelistId;
	}

	public Testcaseignorelist(int testcaseignorelistId, Topology topology,
			Testsuite testsuite, Testcase testcase, String comment) {
		this.testcaseignorelistId = testcaseignorelistId;
		this.topology = topology;
		this.testsuite = testsuite;
		this.testcase = testcase;
		this.comment = comment;
	}

	public int getTestcaseignorelistId() {
		return this.testcaseignorelistId;
	}

	public void setTestcaseignorelistId(int testcaseignorelistId) {
		this.testcaseignorelistId = testcaseignorelistId;
	}

	public Topology getTopology() {
		return this.topology;
	}

	public void setTopology(Topology topology) {
		this.topology = topology;
	}

	public Testsuite getTestsuite() {
		return this.testsuite;
	}

	public void setTestsuite(Testsuite testsuite) {
		this.testsuite = testsuite;
	}

	public Testcase getTestcase() {
		return this.testcase;
	}

	public void setTestcase(Testcase testcase) {
		this.testcase = testcase;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
