package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Testsuite generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testsuite implements java.io.Serializable, IDataTable {

	Integer testSuiteId;
	Role role;
	Product product;
	String testSuiteName;
	String comment;
	Date creationDate;
	Date modificationDate;
	String createdBy;
	String modifiedBy;
	String status;
	Integer elapsedTimeMin;
	Integer elapsedTimeMax;
	String testSuiteFilePath;
	Integer initializationTime;
	Integer executionTime;
	Set<Testcyclesummary> testcyclesummaries = new HashSet<Testcyclesummary> (0);
	Set<Testsuitevariableset>  testsuitevariablesets = new HashSet<Testsuitevariableset> (0);
	Set<Testcase>  testcases = new HashSet<Testcase> (0);
	Set<Testcaseignorelist>  testcaseignorelists = new HashSet<Testcaseignorelist> (0);

	public Testsuite() {
	}

	public Testsuite(int testSuiteId, Role role, String testSuiteName,
			String status, String testSuiteFilePath) {
		this.testSuiteId = testSuiteId;
		this.role = role;
		this.testSuiteName = testSuiteName;
		this.status = status;
		this.testSuiteFilePath = testSuiteFilePath;
	}

	public Testsuite(int testSuiteId, Role role, Product product,
			String testSuiteName, String comment, Date creationDate,
			Date modificationDate, String createdBy, String modifiedBy,
			String status, Integer elapsedTimeMin, Integer elapsedTimeMax,
			String testSuiteFilePath, Integer initializationTime,
			Integer executionTime, Set<Testcyclesummary> testcyclesummaries,
			Set<Testsuitevariableset> testsuitevariablesets, Set<Testcase> testcases, Set<Testcaseignorelist> testcaseignorelists) {
		this.testSuiteId = testSuiteId;
		this.role = role;
		this.product = product;
		this.testSuiteName = testSuiteName;
		this.comment = comment;
		this.creationDate = creationDate;
		this.modificationDate = modificationDate;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.status = status;
		this.elapsedTimeMin = elapsedTimeMin;
		this.elapsedTimeMax = elapsedTimeMax;
		this.testSuiteFilePath = testSuiteFilePath;
		this.initializationTime = initializationTime;
		this.executionTime = executionTime;
		this.testcyclesummaries = testcyclesummaries;
		this.testsuitevariablesets = testsuitevariablesets;
		this.testcases = testcases;
		this.testcaseignorelists = testcaseignorelists;
	}

	public Testsuite(int testSuiteId2) {
		this.testSuiteId = testSuiteId2;
	}

	public Integer getTestSuiteId() {
		return this.testSuiteId;
	}

	public void setTestSuiteId(int testSuiteId) {
		this.testSuiteId = testSuiteId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getTestSuiteName() {
		return this.testSuiteName;
	}

	public void setTestSuiteName(String testSuiteName) {
		this.testSuiteName = testSuiteName;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getElapsedTimeMin() {
		return this.elapsedTimeMin;
	}

	public void setElapsedTimeMin(Integer elapsedTimeMin) {
		this.elapsedTimeMin = elapsedTimeMin;
	}

	public Integer getElapsedTimeMax() {
		return this.elapsedTimeMax;
	}

	public void setElapsedTimeMax(Integer elapsedTimeMax) {
		this.elapsedTimeMax = elapsedTimeMax;
	}

	public String getTestSuiteFilePath() {
		return this.testSuiteFilePath;
	}

	public void setTestSuiteFilePath(String testSuiteFilePath) {
		this.testSuiteFilePath = testSuiteFilePath;
	}

	public Integer getInitializationTime() {
		return this.initializationTime;
	}

	public void setInitializationTime(Integer initializationTime) {
		this.initializationTime = initializationTime;
	}

	public Integer getExecutionTime() {
		return this.executionTime;
	}

	public void setExecutionTime(Integer executionTime) {
		this.executionTime = executionTime;
	}

	public Set<Testcyclesummary> getTestcyclesummaries() {
		return this.testcyclesummaries;
	}

	public void setTestcyclesummaries(Set<Testcyclesummary> testcyclesummaries) {
		this.testcyclesummaries = testcyclesummaries;
	}

	public Set<Testsuitevariableset> getTestsuitevariablesets() {
		return this.testsuitevariablesets;
	}

	public void setTestsuitevariablesets(Set<Testsuitevariableset> testsuitevariablesets) {
		this.testsuitevariablesets = testsuitevariablesets;
	}

	public Set<Testcase> getTestcases() {
		return this.testcases;
	}

	public void setTestcases(Set<Testcase> testcases) {
		this.testcases = testcases;
	}

	public Set<Testcaseignorelist> getTestcaseignorelists() {
		return this.testcaseignorelists;
	}

	public void setTestcaseignorelists(Set<Testcaseignorelist> testcaseignorelists) {
		this.testcaseignorelists = testcaseignorelists;
	}

	@Override
	public void AssignTo(IDataTable iTable) {
    	((Testsuite)iTable).testSuiteId=this.testSuiteId;
		((Testsuite)iTable).role=(this.role);
		((Testsuite)iTable).product=(this.product);
		((Testsuite)iTable).testSuiteName=this.testSuiteName;
		((Testsuite)iTable).comment=this.comment;
		((Testsuite)iTable).creationDate=this.creationDate;
		((Testsuite)iTable).modificationDate=this.modificationDate;
		((Testsuite)iTable).createdBy=this.createdBy;
		((Testsuite)iTable).modifiedBy=this.modifiedBy;
		((Testsuite)iTable).status=this.status;
		((Testsuite)iTable).elapsedTimeMin=this.elapsedTimeMin;
		((Testsuite)iTable).elapsedTimeMax=this.elapsedTimeMax;
		((Testsuite)iTable).testSuiteFilePath=this.testSuiteFilePath;
		((Testsuite)iTable).initializationTime=this.initializationTime;
		((Testsuite)iTable).executionTime=this.executionTime;
	}

	@Override
	public String printString() {
		String str=null;

		
		str="Test Suite Id:"+getTestSuiteId()+"\n";
		str+="Role ID:"+ role.getRoleId()+"\n";
		str+="Product ID:"+ product.getProductId()+"\n";
		str+="Test Suite Name:"+getTestSuiteName()+"\n";
		str+="Comment: "+getComment()+"\n";
		str+="Creation Date:"+getCreationDate()+"\n";
		str+="Modification Date:"+getModificationDate()+"\n";
		str+="Created By:"+getCreatedBy()+"\n";
		str+="Modified By:"+getModifiedBy()+"\n";
		str+="Status:"+getStatus()+"\n";
		str+="Elapsed Time Min:"+getElapsedTimeMin()+"\n";
		str+="Elapsed Time Max:"+getElapsedTimeMax()+"\n";
		str+="Test Plan File Path:"+getTestSuiteFilePath()+"\n";
		str+="Initialization Time:"+getInitializationTime()+"\n";
		str+="Execution Time:"+getExecutionTime()+"\n";
		
		Log.Debug("TestSuite/Print -> " + str);
	
		return str;
	}

}
