package DatabaseLayer;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Testcasevariablevalue generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testcasevariablevalue implements java.io.Serializable, IDataTable {

	int testCaseVariableValueId;
	Testcase testcase;
	Integer variableValuesId;

	public Testcasevariablevalue() {
	}

	public Testcasevariablevalue(int testCaseVariableValueId, Testcase testcase) {
		this.testCaseVariableValueId = testCaseVariableValueId;
		this.testcase = testcase;
	}

	public Testcasevariablevalue(int testCaseVariableValueId,
			Testcase testcase, Integer variableValuesId) {
		this.testCaseVariableValueId = testCaseVariableValueId;
		this.testcase = testcase;
		this.variableValuesId = variableValuesId;
	}

	public int getTestCaseVariableValueId() {
		return this.testCaseVariableValueId;
	}

	public void setTestCaseVariableValueId(int testCaseVariableValueId) {
		this.testCaseVariableValueId = testCaseVariableValueId;
	}

	public Testcase getTestcase() {
		return this.testcase;
	}

	public void setTestcase(Testcase testcase) {
		this.testcase = testcase;
	}

	public Integer getVariableValuesId() {
		return this.variableValuesId;
	}

	public void setVariableValuesId(Integer variableValuesId) {
		this.variableValuesId = variableValuesId;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		
		str="TestCase Variable ValueId: "+getTestCaseVariableValueId()+"\n";
		str+="Testcase ID:"+testcase.getTestCaseId()+"\n";
		str+="variableValuesId: "+getVariableValuesId()+"\n";

		Log.Debug("Testcasevariablevalue:printString : + " + str);
		
		return str;
	}

}
