package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Testcasetorequirementsxref generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testcasetorequirementsxref implements java.io.Serializable {

	int xrefId;
	Requirements requirements;
	Testcase testcase;

	public Testcasetorequirementsxref() {
	}

	public Testcasetorequirementsxref(int xrefId, Requirements requirements,
			Testcase testcase) {
		this.xrefId = xrefId;
		this.requirements = requirements;
		this.testcase = testcase;
	}

	public int getXrefId() {
		return this.xrefId;
	}

	public void setXrefId(int xrefId) {
		this.xrefId = xrefId;
	}

	public Requirements getRequirements() {
		return this.requirements;
	}

	public void setRequirements(Requirements requirements) {
		this.requirements = requirements;
	}

	public Testcase getTestcase() {
		return this.testcase;
	}

	public void setTestcase(Testcase testcase) {
		this.testcase = testcase;
	}

}
