package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Testsuitevariableset generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testsuitevariableset implements java.io.Serializable, IDataTable {

	int testSuiteVariableSetId;
	Testsuitevariables testsuitevariables;
	Testsuite testsuite;
	String variableName;
	String variableDescription;
	Date variableAssociationDate;
	String testPlanConstraint;

	public Testsuitevariableset() {
	}

	public Testsuitevariableset(int testSuiteVariableSetId, Testsuite testsuite) {
		this.testSuiteVariableSetId = testSuiteVariableSetId;
		this.testsuite = testsuite;
	}

	public Testsuitevariableset(int testSuiteVariableSetId,
			Testsuitevariables testsuitevariables, Testsuite testsuite,
			String variableName, String variableDescription,
			Date variableAssociationDate, String testPlanConstraint) {
		this.testSuiteVariableSetId = testSuiteVariableSetId;
		this.testsuitevariables = testsuitevariables;
		this.testsuite = testsuite;
		this.variableName = variableName;
		this.variableDescription = variableDescription;
		this.variableAssociationDate = variableAssociationDate;
		this.testPlanConstraint = testPlanConstraint;
	}

	public int getTestSuiteVariableSetId() {
		return this.testSuiteVariableSetId;
	}

	public void setTestSuiteVariableSetId(int testSuiteVariableSetId) {
		this.testSuiteVariableSetId = testSuiteVariableSetId;
	}

	public Testsuitevariables getTestsuitevariables() {
		return this.testsuitevariables;
	}

	public void setTestsuitevariables(Testsuitevariables testsuitevariables) {
		this.testsuitevariables = testsuitevariables;
	}

	public Testsuite getTestsuite() {
		return this.testsuite;
	}

	public void setTestsuite(Testsuite testsuite) {
		this.testsuite = testsuite;
	}

	public String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(String variableName) {
		this.variableName = variableName;
	}

	public String getVariableDescription() {
		return this.variableDescription;
	}

	public void setVariableDescription(String variableDescription) {
		this.variableDescription = variableDescription;
	}

	public Date getVariableAssociationDate() {
		return this.variableAssociationDate;
	}

	public void setVariableAssociationDate(Date variableAssociationDate) {
		this.variableAssociationDate = variableAssociationDate;
	}

	public String getTestPlanConstraint() {
		return this.testPlanConstraint;
	}

	public void setTestPlanConstraint(String testPlanConstraint) {
		this.testPlanConstraint = testPlanConstraint;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;

		str="testSuiteVariableSetId"+getTestSuiteVariableSetId()+"\n";
		str+=" Testsuite ID:"+ testsuite.getTestSuiteId()+"\n";
		str+=" Testsuitevariables ID:"+ testsuitevariables.getTestSuiteVariableId()+"\n";
		str+="variableName"+getVariableName()+"\n";
		str+="variableDescription"+getVariableDescription()+"\n";
		str+="variableAssociationDate"+getVariableAssociationDate()+"\n";
		str+="testPlanConstraint"+getTestPlanConstraint()+"\n";
		
		Log.Debug("Testsuitevariableset:printString : + " + str);
		return str;
	}

}
