package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Testplan generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testplan implements java.io.Serializable, IDataTable {

	Integer testPlanId;
	Projectphase projectphase;
	Testplantemplate testplantemplate;
	Integer testSuiteListId;
	String codeName;
	Date creationDate;
	Date modificationDate;
	String createdBy;
	String modifiedBy;
	String status;
	Integer productId;
	String comment;
	Integer topologySetListId;
	 Set<Testcycle> testcycles = new HashSet<Testcycle>(0);
	 Set<TopologysetTopologysetlistXref> topologysetlists = new HashSet<TopologysetTopologysetlistXref>(0);
	 Set<Projectphase> projectphases = new HashSet<Projectphase>(0);

	public Testplan() {
	}

	public Testplan(int testPlanId, Projectphase projectphase, Integer productId) {
		this.testPlanId = testPlanId;
		this.projectphase = projectphase;
		this.productId = productId;
	}

	public Testplan(int testPlanId, Projectphase projectphase,
			Testplantemplate testplantemplate, Integer testSuiteListId,
			String codeName, Date creationDate, Date modificationDate,
			String createdBy, String modifiedBy, String status, Integer productId,
			String comment, Integer topologySetListId, Set<Testcycle> testcycles) {
		this.testPlanId = testPlanId;
		this.projectphase = projectphase;
		this.testplantemplate = testplantemplate;
		this.testSuiteListId = testSuiteListId;
		this.codeName = codeName;
		this.creationDate = creationDate;
		this.modificationDate = modificationDate;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.status = status;
		this.productId = productId;
		this.comment = comment;
		this.topologySetListId = topologySetListId;
		this.testcycles = testcycles;
	}

	public Testplan(int testPlanId) {
		this.testPlanId = testPlanId;
	}

	public int getTestPlanId() {
		return this.testPlanId;
	}

	public void setTestPlanId(int testPlanId) {
		this.testPlanId = testPlanId;
	}

	public Projectphase getProjectphase() {
		return this.projectphase;
	}

	public void setProjectphase(Projectphase projectphase) {
		this.projectphase = projectphase;
	}

	public Testplantemplate getTestplantemplate() {
		return this.testplantemplate;
	}

	public void setTestplantemplate(Testplantemplate testplantemplate) {
		this.testplantemplate = testplantemplate;
	}

	public Integer getTestSuiteListId() {
		return this.testSuiteListId;
	}

	public void setTestSuiteListId(Integer testSuiteListId) {
		this.testSuiteListId = testSuiteListId;
	}

	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Integer getTopologySetListId() {
		return this.topologySetListId;
	}

	public void setTopologySetListId(Integer topologySetListId) {
		this.topologySetListId = topologySetListId;
	}

	public Set<Testcycle> getTestcycles() {
		return this.testcycles;
	}

	public void setTestcycles(Set<Testcycle> testcycles) {
		this.testcycles = testcycles;
	}

	@Override
	public void AssignTo(IDataTable iTable) {
		((Testplan)iTable).testPlanId=this.testPlanId;
		((Testplan)iTable).testplantemplate=this.testplantemplate;
		((Testplan)iTable).topologySetListId=this.topologySetListId;
		((Testplan)iTable).testSuiteListId=this.testSuiteListId;
		((Testplan)iTable).creationDate=this.creationDate;
		((Testplan)iTable).modificationDate=this.modificationDate;
		((Testplan)iTable).createdBy=this.createdBy;
		((Testplan)iTable).modifiedBy=this.modifiedBy;
		((Testplan)iTable).status=this.status;
		((Testplan)iTable).productId=this.productId;
		((Testplan)iTable).topologySetListId=this.topologySetListId;
		((Testplan)iTable).codeName=this.codeName;
	}

	@Override
	public String printString() {
		String str = "Test Plan Id: "+getTestPlanId()+"\n";
		if(testplantemplate==null)
			str+="Testplantemplate ID : null\n";
		else
			str+="Testplantemplate ID:"+ testplantemplate.getTemplateId()+"\n";
		str+="Test Suite List Id: "+getTestSuiteListId()+"\n";
		str+="Creation Date: "+getCreationDate()+"\n";
		str+="Modification Date: "+getModificationDate()+"\n";
		str+="Created By: "+getCreatedBy()+"\n";
		str+="Modified By: "+getModifiedBy()+"\n";
		str+="Status: "+getStatus()+"\n";
		str+="Product: "+getProductId()+"\n";
		str+="Comment: "+getComment()+"\n";
		str+="Topology Set List Id: "+getTopologySetListId()+"\n";
		str+="Code Name: "+getCodeName()+"\n";
		Log.Debug("TestPlan/Print -> " + str);
		
		return str;
	}

}
