package DatabaseLayer;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * TestsuiteTestsuitelistXref generated by hbm2java
 */
@SuppressWarnings("serial")
public class TestsuiteTestsuitelistXref implements java.io.Serializable, IDataTable {

	
	Integer testsuiteTestsuitlistXrefId;
	Integer testsuiteId;
	Integer testsuitelistId;

	public TestsuiteTestsuitelistXref() {
	}

	public TestsuiteTestsuitelistXref(int testsuiteTestsuitlistXrefId,
			int testsuiteId, int testsuitelistId) {
		this.testsuiteTestsuitlistXrefId = testsuiteTestsuitlistXrefId;
		this.testsuiteId = testsuiteId;
		this.testsuitelistId = testsuitelistId;
	}

	public Integer getTestsuiteTestsuitlistXrefId() {
		return this.testsuiteTestsuitlistXrefId;
	}

	public void setTestsuiteTestsuitlistXrefId(Integer testsuiteTestsuitlistXrefId) {
		this.testsuiteTestsuitlistXrefId = testsuiteTestsuitlistXrefId;
	}

	public Integer getTestsuiteId() {
		return this.testsuiteId;
	}

	public void setTestsuiteId(Integer testsuiteId) {
		this.testsuiteId = testsuiteId;
	}

	public Integer getTestsuitelistId() {
		return this.testsuitelistId;
	}

	public void setTestsuitelistId(Integer testsuitelistId) {
		this.testsuitelistId = testsuitelistId;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		str="Test Suite List Id: "+getTestsuitelistId()+"\n";
		str+="Test Suite Id: "+getTestsuiteId()+"\n";
		
		Log.Debug("TestsuiteTestsuitelistxref:printString : + " + str);
		return str;
	}

}
