package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Testcycletopologyset generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testcycletopologyset implements java.io.Serializable, IDataTable {

	Integer testCycleTopologySetId;
	Topology topology;
	Role role;
	Testcycle testcycle;
	Machinecatalog machinecatalog;
	String buildNo;
	Topologyset topologyset;
	Set<Testexecutiondetails> testexecutiondetailses = new HashSet<Testexecutiondetails> (0);

	public Testcycletopologyset() {
	}

	public Testcycletopologyset(int testCycleTopologySetId) {
		this.testCycleTopologySetId = testCycleTopologySetId;
	}

	public Testcycletopologyset(int testCycleTopologySetId, Topology topology,
			Role role, Testcycle testcycle, Machinecatalog machinecatalog,
			String buildNo, Set<Testexecutiondetails> testexecutiondetailses) {
		this.testCycleTopologySetId = testCycleTopologySetId;
		this.topology = topology;
		this.role = role;
		this.testcycle = testcycle;
		this.machinecatalog = machinecatalog;
		this.buildNo = buildNo;
		this.testexecutiondetailses = testexecutiondetailses;
	}

	public Integer getTestCycleTopologySetId() {
		return this.testCycleTopologySetId;
	}

	public void setTestCycleTopologySetId(int testCycleTopologySetId) {
		this.testCycleTopologySetId = testCycleTopologySetId;
	}

	public Topology getTopology() {
		return this.topology;
	}

	public void setTopology(Topology topology) {
		this.topology = topology;
	}
	
	public Topologyset getTopologyset() {
		return this.topologyset;
	}

	public void setTopologyset(Topologyset topologyset) {
		this.topologyset = topologyset;
	}
	
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Testcycle getTestcycle() {
		return this.testcycle;
	}

	public void setTestcycle(Testcycle testcycle) {
		this.testcycle = testcycle;
	}

	public Machinecatalog getMachinecatalog() {
		return this.machinecatalog;
	}

	public void setMachinecatalog(Machinecatalog machinecatalog) {
		this.machinecatalog = machinecatalog;
	}

	public String getBuildNo() {
		return this.buildNo;
	}

	public void setBuildNo(String buildNo) {
		this.buildNo = buildNo;
	}

	public Set<Testexecutiondetails> getTestexecutiondetailses() {
		return this.testexecutiondetailses;
	}

	public void setTestexecutiondetailses(Set<Testexecutiondetails> testexecutiondetailses) {
		this.testexecutiondetailses = testexecutiondetailses;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		
		str="Test Cycle TopologySet Id: "+getTestCycleTopologySetId()+"\n";
		str+="Role ID:"+ role.getRoleId()+"\n";
		str+="TopologyID:"+ topology.getTopologyId()+"\n";
		str+="Testcycle ID:"+ testcycle.getTestCycleId()+"\n";
		str+="Build No: "+getBuildNo()+"\n"; 
		str+="TopologySet ID:"+ topologyset.getTopologySetId() + "\n";
		
		Log.Debug("TestCycleTopologyset:printString : + " + str);
		
		return str;
	}

}
