package DatabaseLayer;
import DatabaseLayer.DataClasses.IDataTable;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Topologysetlist generated by hbm2java
 */
@SuppressWarnings("serial")
public class Topologysetlist implements java.io.Serializable, IDataTable {

	Integer topologySetListId;
	String topologySetListDescription;

	Topologysetlist() {
	}

	public Topologysetlist(int topologySetListId,
			String topologySetListDescription) {
		this.topologySetListId = topologySetListId;
		this.topologySetListDescription = topologySetListDescription;
	}

	public int getTopologySetListId() {
		return this.topologySetListId;
	}

	public void setTopologySetListId(int topologySetListId) {
		this.topologySetListId = topologySetListId;
	}

	public String getTopologySetListDescription() {
		return this.topologySetListDescription;
	}

	public void setTopologySetListDescription(String topologySetListDescription) {
		this.topologySetListDescription = topologySetListDescription;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		// TODO Auto-generated method stub
		return null;
	}

}
