package DatabaseLayer;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * TopologyTopologysetXref generated by hbm2java
 */
@SuppressWarnings("serial")
public class TopologyTopologysetXref implements java.io.Serializable, IDataTable {

	Integer topologyTopologysetXref;
	Integer topologysetId;
	Integer topologyId;

	public TopologyTopologysetXref() {
	}

	public TopologyTopologysetXref(int topologyTopologysetXref,
			int topologysetId, int topologyId) {
		this.topologyTopologysetXref = topologyTopologysetXref;
		this.topologysetId = topologysetId;
		this.topologyId = topologyId;
	}

	public Integer getTopologyTopologysetXref() {
		return this.topologyTopologysetXref;
	}

	public void setTopologyTopologysetXref(int topologyTopologysetXref) {
		this.topologyTopologysetXref = topologyTopologysetXref;
	}

	public Integer getTopologysetId() {
		return this.topologysetId;
	}

	public void setTopologysetId(int topologysetId) {
		this.topologysetId = topologysetId;
	}

	public int getTopologyId() {
		return this.topologyId;
	}

	public void setTopologyId(int topologyId) {
		this.topologyId = topologyId;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		str="Topology Set Id:"+getTopologysetId()+"\n";
		str+="Topology ID:"+ getTopologyId()+"\n";
		
		Log.Debug("Topologyset:printString : + " + str);
		return str;
	}

}
