package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Topology generated by hbm2java
 */
@SuppressWarnings("serial")
public class Topology implements java.io.Serializable, IDataTable {

	Integer topologyId;
	Role role;
	Machinecatalog machinecatalog;
	String rationale;
	String osArchitecture;
	String osVersion;
	String osLanguageId;
	String osServicePack;
	String baseVmIdentifier;
	Set<Testcycletopologyset> testcycletopologysets = new HashSet<Testcycletopologyset>(0);
	Set<Topologyattributes> topologyattributeses = new HashSet<Topologyattributes>(0);
	Set<Testcaseignorelist> testcaseignorelists = new HashSet<Testcaseignorelist>(0);

	public Topology() {
	}

	public Topology(int topologyId, Role role) {
		this.topologyId = topologyId;
		this.role = role;
	}

	public Topology(int topologyId, Role role, Machinecatalog machinecatalog,
			String rationale, String osArchitecture, String osVersion,
			String osLanguageId, String osServicePack, String baseVmIdentifier,
			Set<Testcycletopologyset> testcycletopologysets, Set<Topologyattributes> topologyattributeses,
			Set<Testcaseignorelist> testcaseignorelists) {
		this.topologyId = topologyId;
		this.role = role;
		this.machinecatalog = machinecatalog;
		this.rationale = rationale;
		this.osArchitecture = osArchitecture;
		this.osVersion = osVersion;
		this.osLanguageId = osLanguageId;
		this.osServicePack = osServicePack;
		this.baseVmIdentifier = baseVmIdentifier;
		this.testcycletopologysets = testcycletopologysets;
		this.topologyattributeses = topologyattributeses;
		this.testcaseignorelists = testcaseignorelists;
	}

	public Topology(int topologyId) {
		this.topologyId = topologyId;
	}

	public int getTopologyId() {
		return this.topologyId;
	}

	public void setTopologyId(int topologyId) {
		this.topologyId = topologyId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Machinecatalog getMachinecatalog() {
		return this.machinecatalog;
	}

	public void setMachinecatalog(Machinecatalog machinecatalog) {
		this.machinecatalog = machinecatalog;
	}

	public String getRationale() {
		return this.rationale;
	}

	public void setRationale(String rationale) {
		this.rationale = rationale;
	}

	public String getOsArchitecture() {
		return this.osArchitecture;
	}

	public void setOsArchitecture(String osArchitecture) {
		this.osArchitecture = osArchitecture;
	}

	public String getOsVersion() {
		return this.osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}

	public String getOsLanguageId() {
		return this.osLanguageId;
	}

	public void setOsLanguageId(String osLanguageId) {
		this.osLanguageId = osLanguageId;
	}

	public String getOsServicePack() {
		return this.osServicePack;
	}

	public void setOsServicePack(String osServicePack) {
		this.osServicePack = osServicePack;
	}

	public String getBaseVmIdentifier() {
		return this.baseVmIdentifier;
	}

	public void setBaseVmIdentifier(String baseVmIdentifier) {
		this.baseVmIdentifier = baseVmIdentifier;
	}

	public Set<Testcycletopologyset> getTestcycletopologysets() {
		return this.testcycletopologysets;
	}

	public void setTestcycletopologysets(Set<Testcycletopologyset> testcycletopologysets) {
		this.testcycletopologysets = testcycletopologysets;
	}

	public Set<Topologyattributes> getTopologyattributeses() {
		return this.topologyattributeses;
	}

	public void setTopologyattributeses(Set<Topologyattributes> topologyattributeses) {
		this.topologyattributeses = topologyattributeses;
	}

	public Set<Testcaseignorelist> getTestcaseignorelists() {
		return this.testcaseignorelists;
	}

	public void setTestcaseignorelists(Set<Testcaseignorelist> testcaseignorelists) {
		this.testcaseignorelists = testcaseignorelists;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		
		str="TopologyId:"+getTopologyId()+"\n";
		str+="Role ID:"+role.getRoleId()+"\n";
		str+="Machinecatalog ID:"+ machinecatalog.getMachineCatalogId()+"\n";
		str+="Rationale:"+getRationale()+"\n";
		str+="OS Architecture:"+getOsArchitecture()+"\n";
		str+="OS Version:"+getOsVersion()+"\n";
		str+="OS LanguageId:"+getOsLanguageId()+"\n";
		str+="OS Service Pack:"+getOsServicePack()+"\n";
		str+="Base Vm Identifier:"+getBaseVmIdentifier()+"\n";
		
		Log.Debug("Topology/Print -> " + str);
		return str;
	}

}
