package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import DatabaseLayer.DataClasses.IDataTable;

/**
 * Topologyset generated by hbm2java
 */
@SuppressWarnings("serial")
public class Topologyset implements java.io.Serializable, IDataTable {

	Integer topologySetId;
	Set<Testcycledetail> testcycledetails = new HashSet<Testcycledetail>(0);
	Set<Testcyclesummary> testcyclesummaries = new HashSet<Testcyclesummary>(0);

	public Topologyset() {
	}

	public Topologyset(int topologySetId) {
		this.topologySetId = topologySetId;
	}

	public Topologyset(int topologySetId, Set<Testcycledetail> testcycledetails,
			Set<Testcyclesummary> testcyclesummaries) {
		this.topologySetId = topologySetId;
		this.testcycledetails = testcycledetails;
		this.testcyclesummaries = testcyclesummaries;
	}

	public Integer getTopologySetId() {
		return this.topologySetId;
	}

	public void setTopologySetId(int topologySetId) {
		this.topologySetId = topologySetId;
	}

	public Set<Testcycledetail> getTestcycledetails() {
		return this.testcycledetails;
	}

	public void setTestcycledetails(Set<Testcycledetail> testcycledetails) {
		this.testcycledetails = testcycledetails;
	}

	public Set<Testcyclesummary> getTestcyclesummaries() {
		return this.testcyclesummaries;
	}

	public void setTestcyclesummaries(Set<Testcyclesummary> testcyclesummaries) {
		this.testcyclesummaries = testcyclesummaries;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		// TODO Auto-generated method stub
		return null;
	}

}
