package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Bugs generated by hbm2java
 */
@SuppressWarnings("serial")
public class Bugs implements java.io.Serializable {

	int bugId;
	Product product;
	String synopsis;
	String priority;
	String component;
	String description;
	String foundIn;
	String foundVia;
	String severity;
	String status;
	String assignedTo;

	public Bugs() {
	}

	public Bugs(int bugId, Product product) {
		this.bugId = bugId;
		this.product = product;
	}

	public Bugs(int bugId, Product product, String synopsis, String priority,
			String component, String description, String foundIn,
			String foundVia, String severity, String status, String assignedTo) {
		this.bugId = bugId;
		this.product = product;
		this.synopsis = synopsis;
		this.priority = priority;
		this.component = component;
		this.description = description;
		this.foundIn = foundIn;
		this.foundVia = foundVia;
		this.severity = severity;
		this.status = status;
		this.assignedTo = assignedTo;
	}

	public int getBugId() {
		return this.bugId;
	}

	public void setBugId(int bugId) {
		this.bugId = bugId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getSynopsis() {
		return this.synopsis;
	}

	public void setSynopsis(String synopsis) {
		this.synopsis = synopsis;
	}

	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public String getComponent() {
		return this.component;
	}

	public void setComponent(String component) {
		this.component = component;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFoundIn() {
		return this.foundIn;
	}

	public void setFoundIn(String foundIn) {
		this.foundIn = foundIn;
	}

	public String getFoundVia() {
		return this.foundVia;
	}

	public void setFoundVia(String foundVia) {
		this.foundVia = foundVia;
	}

	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

}
