package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Build generated by hbm2java
 */
@SuppressWarnings("serial")
public class Build implements java.io.Serializable, IDataTable {

	int buildId;
	Projectphase projectphase;
	String buildTag;
	Date buildStartDate;
	Date buildEndDate;

	public Build() {
	}

	public Build(int buildId, Projectphase projectphase, String buildTag) {
		this.buildId = buildId;
		this.projectphase = projectphase;
		this.buildTag = buildTag;
	}

	public Build(int buildId, Projectphase projectphase, String buildTag,
			Date buildStartDate, Date buildEndDate) {
		this.buildId = buildId;
		this.projectphase = projectphase;
		this.buildTag = buildTag;
		this.buildStartDate = buildStartDate;
		this.buildEndDate = buildEndDate;
	}

	public int getBuildId() {
		return this.buildId;
	}

	public void setBuildId(int buildId) {
		this.buildId = buildId;
	}

	public Projectphase getProjectphase() {
		return this.projectphase;
	}

	public void setProjectphase(Projectphase projectphase) {
		this.projectphase = projectphase;
	}

	public String getBuildTag() {
		return this.buildTag;
	}

	public void setBuildTag(String buildTag) {
		this.buildTag = buildTag;
	}

	public Date getBuildStartDate() {
		return this.buildStartDate;
	}

	public void setBuildStartDate(Date buildStartDate) {
		this.buildStartDate = buildStartDate;
	}

	public Date getBuildEndDate() {
		return this.buildEndDate;
	}

	public void setBuildEndDate(Date buildEndDate) {
		this.buildEndDate = buildEndDate;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		
		str="Build ID :"+getBuildId()+"\n";
		str+="Project Phasae ID: "+projectphase.getProjectPhaseId()+"\n";
		str+="Build Tag " +getBuildTag()+"\n"+"Build Start Time" +getBuildStartDate();
		str+="\n"+"Build End Date"+getBuildEndDate()+"\n";

		Log.Debug("Build:printString : + " + str);
		return str;
	}

}
