package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Machinecatalog generated by hbm2java
 */
@SuppressWarnings("serial")
public class Machinecatalog implements java.io.Serializable, IDataTable {

	Integer machineCatalogId;
	Applicationlist applicationlist;
	Integer hostmachineId;
	String description;
	String hostedName;
	byte isVm;
	String domain;
	String ipAddress;
	String status;
	String vmimagePath;
	String snapshotName;
	Date creationDate;
	Date modificationDate;
	String architecture;
	String osVersion;
	String osServicePack;
	String osLanguage;
	Set<Topology>  topologies = new HashSet<Topology> (0);
	Set<Testcycletopologyset>  testcycletopologysets = new HashSet<Testcycletopologyset> (0);

	public Machinecatalog() {
	}

	public Machinecatalog(int machineCatalogId,
			Applicationlist applicationlist, String hostedName, byte isVm,
			String domain, String ipAddress, String status,
			String architecture, String osVersion, String osServicePack,
			String osLanguage) {
		this.machineCatalogId = machineCatalogId;
		this.applicationlist = applicationlist;
		this.hostedName = hostedName;
		this.isVm = isVm;
		this.domain = domain;
		this.ipAddress = ipAddress;
		this.status = status;
		this.architecture = architecture;
		this.osVersion = osVersion;
		this.osServicePack = osServicePack;
		this.osLanguage = osLanguage;
	}

	public Machinecatalog(int machineCatalogId,
			Applicationlist applicationlist, Integer hostmachineId,
			String description, String hostedName, byte isVm, String domain,
			String ipAddress, String status, String vmimagePath,
			String snapshotName, Date creationDate, Date modificationDate,
			String architecture, String osVersion, String osServicePack,
			String osLanguage, Set<Topology> topologies, Set<Testcycletopologyset> testcycletopologysets) {
		this.machineCatalogId = machineCatalogId;
		this.applicationlist = applicationlist;
		this.hostmachineId = hostmachineId;
		this.description = description;
		this.hostedName = hostedName;
		this.isVm = isVm;
		this.domain = domain;
		this.ipAddress = ipAddress;
		this.status = status;
		this.vmimagePath = vmimagePath;
		this.snapshotName = snapshotName;
		this.creationDate = creationDate;
		this.modificationDate = modificationDate;
		this.architecture = architecture;
		this.osVersion = osVersion;
		this.osServicePack = osServicePack;
		this.osLanguage = osLanguage;
		this.topologies = topologies;
		this.testcycletopologysets = testcycletopologysets;
	}

	public Machinecatalog(int machineCatalogId) {
		this.machineCatalogId = machineCatalogId;
	}

	public Integer getMachineCatalogId() {
		return this.machineCatalogId;
	}

	public void setMachineCatalogId(int machineCatalogId) {
		this.machineCatalogId = machineCatalogId;
	}

	public Applicationlist getApplicationlist() {
		return this.applicationlist;
	}

	public void setApplicationlist(Applicationlist applicationlist) {
		this.applicationlist = applicationlist;
	}

	public Integer getHostmachineId() {
		return this.hostmachineId;
	}

	public void setHostmachineId(Integer hostmachineId) {
		this.hostmachineId = hostmachineId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getHostedName() {
		return this.hostedName;
	}

	public void setHostedName(String hostedName) {
		this.hostedName = hostedName;
	}

	public byte getIsVm() {
		return this.isVm;
	}

	public void setIsVm(byte isVm) {
		this.isVm = isVm;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getVmimagePath() {
		return this.vmimagePath;
	}

	public void setVmimagePath(String vmimagePath) {
		this.vmimagePath = vmimagePath;
	}

	public String getSnapshotName() {
		return this.snapshotName;
	}

	public void setSnapshotName(String snapshotName) {
		this.snapshotName = snapshotName;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(Date modificationDate) {
		this.modificationDate = modificationDate;
	}

	public String getArchitecture() {
		return this.architecture;
	}

	public void setArchitecture(String architecture) {
		this.architecture = architecture;
	}

	public String getOsVersion() {
		return this.osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}

	public String getOsServicePack() {
		return this.osServicePack;
	}

	public void setOsServicePack(String osServicePack) {
		this.osServicePack = osServicePack;
	}

	public String getOsLanguage() {
		return this.osLanguage;
	}

	public void setOsLanguage(String osLanguage) {
		this.osLanguage = osLanguage;
	}

	public Set<Topology> getTopologies() {
		return this.topologies;
	}

	public void setTopologies(Set<Topology> topologies) {
		this.topologies = topologies;
	}

	public Set<Testcycletopologyset> getTestcycletopologysets() {
		return this.testcycletopologysets;
	}

	public void setTestcycletopologysets(Set<Testcycletopologyset> testcycletopologysets) {
		this.testcycletopologysets = testcycletopologysets;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		
		
		str="Machine CatalogId :"+getMachineCatalogId()+"\n";
		str+="Applicationlist ID:"+applicationlist.getApplicationListId()+"\n";
		str+="Host MachineId: "+getHostmachineId()+"\n";
		str+="Hosted Name: "+getHostedName()+"\n";
		str+="Is Vm: "+getIsVm()+"\n";
		str+="Domain: "+getDomain()+"\n";
		str+="Ip Address: "+getIpAddress()+"\n";
		str+="Status: "+getStatus()+"\n";
		str+="Vm ImagePath: "+getVmimagePath()+"\n";
		str+="Snapshot Name: "+getSnapshotName()+"\n";
		str+="Creation Date: "+getCreationDate()+"\n";
		str+="Modification Date: "+getModificationDate()+"\n";
		str+="Architecture: "+getArchitecture()+"\n";
		str+="OS Version: "+getOsVersion()+"\n";
		str+="OS ServicePack: "+getOsServicePack()+"\n";
		str+="OS Language: "+getOsLanguage()+"\n";
		
		Log.Debug("Machinecatalog:printString : + " + str);
		
		return str;
	}

}
