package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Product generated by hbm2java
 */
@SuppressWarnings("serial")
public class Product implements java.io.Serializable, IDataTable {

	int productId;
	String productName;
	String description;
	String createdBy;
	Date creationDate;
	Set<Features> featureses = new HashSet<Features> (0);
	Set<Bugs> bugses = new HashSet<Bugs> (0);
	Set<Releases>  releaseses = new HashSet<Releases> (0);
	Set<Testplantemplate>  testplantemplates = new HashSet<Testplantemplate> (0);
	Set<Testsuite> testsuites = new HashSet<Testsuite> (0);

	public Product() {
	}

	public Product(int productId, String productName, String createdBy,
			Date creationDate) {
		this.productId = productId;
		this.productName = productName;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
	}

	public Product(int productId, String productName, String description,
			String createdBy, Date creationDate, Set<Features> featureses, Set<Bugs> bugses,
			Set<Releases> releaseses, Set<Testplantemplate> testplantemplates, Set<Testsuite> testsuites) {
		this.productId = productId;
		this.productName = productName;
		this.description = description;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.featureses = featureses;
		this.bugses = bugses;
		this.releaseses = releaseses;
		this.testplantemplates = testplantemplates;
		this.testsuites = testsuites;
	}

	public Product(int productId) {
		this.productId = productId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Set<Features> getFeatureses() {
		return this.featureses;
	}

	public void setFeatureses(Set<Features> featureses) {
		this.featureses = featureses;
	}

	public Set<Bugs> getBugses() {
		return this.bugses;
	}

	public void setBugses(Set<Bugs> bugses) {
		this.bugses = bugses;
	}

	public Set<Releases> getReleaseses() {
		return this.releaseses;
	}

	public void setReleaseses(Set<Releases> releaseses) {
		this.releaseses = releaseses;
	}

	public Set<Testplantemplate> getTestplantemplates() {
		return this.testplantemplates;
	}

	public void setTestplantemplates(Set<Testplantemplate> testplantemplates) {
		this.testplantemplates = testplantemplates;
	}

	public Set<Testsuite> getTestsuites() {
		return this.testsuites;
	}

	public void setTestsuites(Set<Testsuite> testsuites) {
		this.testsuites = testsuites;
	}

	public void AssignTo(IDataTable iTable)
    {
    	
    }
	
	public String printString()
	{
		String str=null; 
		
		str="Product ID :"+getProductId();
		str+="\n";
		str+="Product Name:"+getProductName();
		str+="\n";
		str+="Product Description: "+getDescription();
		str+="\n";
		str+="Product Created By: :"+getCreatedBy();
		str+="\n";
		str+="Product Creation Date:"+getCreationDate();
		Log.Debug("Product:printString : + " + str);
		return str;
		
	}

}
