package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import logs.Log;
import BusinessLayer.TestSuite;
import DatabaseLayer.DataClasses.IDataTable;

/**
 * Role generated by hbm2java
 */
@SuppressWarnings("serial")
public class Role implements java.io.Serializable, IDataTable {

	Integer roleId;
	String roleName;
	String description;
	Set<Topology> topologies = new HashSet<Topology> (0);
	Set<Roleattributes> roleattributeses = new HashSet<Roleattributes> (0);
	Set<Testcycletopologyset> testcycletopologysets = new HashSet<Testcycletopologyset>(0);
	Set<TestSuite> testsuites = new HashSet<TestSuite> (0);

	public Role() {
	}

	public Role(int roleId, String roleName) {
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public Role(int roleId, String roleName, String description,
			Set<Topology> topologies, Set<Roleattributes> roleattributeses, Set<Testcycletopologyset> testcycletopologysets,
			Set<TestSuite> testsuites) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.description = description;
		this.topologies = topologies;
		this.roleattributeses = roleattributeses;
		this.testcycletopologysets = testcycletopologysets;
		this.testsuites = testsuites;
	}

	public Role(Integer roleId)
	{
		this.roleId=roleId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Topology> getTopologies() {
		return this.topologies;
	}

	public void setTopologies(Set<Topology> topologies) {
		this.topologies = topologies;
	}

	public Set<Roleattributes> getRoleattributeses() {
		return this.roleattributeses;
	}

	public void setRoleattributeses(Set<Roleattributes> roleattributeses) {
		this.roleattributeses = roleattributeses;
	}

	public Set<Testcycletopologyset> getTestcycletopologysets() {
		return this.testcycletopologysets;
	}

	public void setTestcycletopologysets(Set<Testcycletopologyset> testcycletopologysets) {
		this.testcycletopologysets = testcycletopologysets;
	}

	public Set<TestSuite> getTestsuites() {
		return this.testsuites;
	}

	public void setTestsuites(Set<TestSuite> testsuites) {
		this.testsuites = testsuites;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		
		str="Role Id:"+getRoleId()+"\n";
		str+="Role Name:"+getRoleName()+"\n";
		str+="Description:"+getDescription()+"\n";
		Log.Debug("Role:printString : + " + str);
		
		return str;
	}

}
