package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Testcyclesummary generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testcyclesummary implements java.io.Serializable {

	int testCycleSummaryId;
	Testcycle testcycle;
	Testsuite testsuite;
	Topologyset topologyset;
	Integer testCaseExecuted;
	Integer testCaseFailed;
	Integer testCaseTotal;
	String testPlanName;
	String status;

	public Testcyclesummary() {
	}

	public Testcyclesummary(int testCycleSummaryId) {
		this.testCycleSummaryId = testCycleSummaryId;
	}

	public Testcyclesummary(int testCycleSummaryId, Testcycle testcycle,
			Testsuite testsuite, Topologyset topologyset,
			Integer testCaseExecuted, Integer testCaseFailed,
			Integer testCaseTotal, String testPlanName, String status) {
		this.testCycleSummaryId = testCycleSummaryId;
		this.testcycle = testcycle;
		this.testsuite = testsuite;
		this.topologyset = topologyset;
		this.testCaseExecuted = testCaseExecuted;
		this.testCaseFailed = testCaseFailed;
		this.testCaseTotal = testCaseTotal;
		this.testPlanName = testPlanName;
		this.status = status;
	}

	public int getTestCycleSummaryId() {
		return this.testCycleSummaryId;
	}

	public void setTestCycleSummaryId(int testCycleSummaryId) {
		this.testCycleSummaryId = testCycleSummaryId;
	}

	public Testcycle getTestcycle() {
		return this.testcycle;
	}

	public void setTestcycle(Testcycle testcycle) {
		this.testcycle = testcycle;
	}

	public Testsuite getTestsuite() {
		return this.testsuite;
	}

	public void setTestsuite(Testsuite testsuite) {
		this.testsuite = testsuite;
	}

	public Topologyset getTopologyset() {
		return this.topologyset;
	}

	public void setTopologyset(Topologyset topologyset) {
		this.topologyset = topologyset;
	}

	public Integer getTestCaseExecuted() {
		return this.testCaseExecuted;
	}

	public void setTestCaseExecuted(Integer testCaseExecuted) {
		this.testCaseExecuted = testCaseExecuted;
	}

	public Integer getTestCaseFailed() {
		return this.testCaseFailed;
	}

	public void setTestCaseFailed(Integer testCaseFailed) {
		this.testCaseFailed = testCaseFailed;
	}

	public Integer getTestCaseTotal() {
		return this.testCaseTotal;
	}

	public void setTestCaseTotal(Integer testCaseTotal) {
		this.testCaseTotal = testCaseTotal;
	}

	public String getTestPlanName() {
		return this.testPlanName;
	}

	public void setTestPlanName(String testPlanName) {
		this.testPlanName = testPlanName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
