package DatabaseLayer;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import BusinessLayer.TestPlan;

/**
 * Testplantemplate generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testplantemplate implements java.io.Serializable {

	int templateId;
	Product product;
	Integer testSuiteListId;
	Integer topologysetlistId;
	String comment;
	Date creationDate;
	Date modifiedDate;
	String createdBy;
	String modifiedBy;
	Set<TestPlan> testplans = new HashSet<TestPlan> (0);

	public Testplantemplate() {
	}

	public Testplantemplate(int templateId, Product product) {
		this.templateId = templateId;
		this.product = product;
	}

	public Testplantemplate(int templateId, Product product,
			Integer testSuiteListId, Integer topologysetlistId, String comment,
			Date creationDate, Date modifiedDate, String createdBy,
			String modifiedBy, Set<TestPlan> testplans) {
		this.templateId = templateId;
		this.product = product;
		this.testSuiteListId = testSuiteListId;
		this.topologysetlistId = topologysetlistId;
		this.comment = comment;
		this.creationDate = creationDate;
		this.modifiedDate = modifiedDate;
		this.createdBy = createdBy;
		this.modifiedBy = modifiedBy;
		this.testplans = testplans;
	}

	public Testplantemplate(int templateId) {
		this.templateId = templateId;
	}

	public int getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(int templateId) {
		this.templateId = templateId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Integer getTestSuiteListId() {
		return this.testSuiteListId;
	}

	public void setTestSuiteListId(Integer testSuiteListId) {
		this.testSuiteListId = testSuiteListId;
	}

	public Integer getTopologysetlistId() {
		return this.topologysetlistId;
	}

	public void setTopologysetlistId(Integer topologysetlistId) {
		this.topologysetlistId = topologysetlistId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<TestPlan> getTestplans() {
		return this.testplans;
	}

	public void setTestplans(Set<TestPlan> testplans) {
		this.testplans = testplans;
	}

}
