package DatabaseLayer;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Testsuitelist generated by hbm2java
 */
@SuppressWarnings("serial")
public class Testsuitelist implements java.io.Serializable, IDataTable {

	 int testSuiteListId;
	String testSuiteListDescription;

	public Testsuitelist() {
	}

	public Testsuitelist(int testSuiteListId) {
		this.testSuiteListId = testSuiteListId;
	}

	public Testsuitelist(int testSuiteListId, String testSuiteListDescription) {
		this.testSuiteListId = testSuiteListId;
		this.testSuiteListDescription = testSuiteListDescription;
	}

	public int getTestSuiteListId() {
		return this.testSuiteListId;
	}

	public void setTestSuiteListId(int testSuiteListId) {
		this.testSuiteListId = testSuiteListId;
	}

	public String getTestSuiteListDescription() {
		return this.testSuiteListDescription;
	}

	public void setTestSuiteListDescription(String testSuiteListDescription) {
		this.testSuiteListDescription = testSuiteListDescription;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;
		str="Test Suite List Id: "+getTestSuiteListId()+"\n";
		str+="Test Suite List Description: "+getTestSuiteListDescription()+"\n";
		
		Log.Debug("Testsuitelist:printString : + " + str);
		return str;
	}

}
