package DatabaseLayer;

import logs.Log;
import DatabaseLayer.DataClasses.IDataTable;

// Generated Nov 2, 2009 5:59:33 PM by Hibernate Tools 3.2.4.GA

/**
 * Variablevalues generated by hbm2java
 */
@SuppressWarnings("serial")
public class Variablevalues implements java.io.Serializable, IDataTable {

	//private int variableValuesId;
	int variableValuesId;
	//private Testsuitevariables testsuitevariables;
	Testsuitevariables testsuitevariables;
	//private String variableValue;
	String variableValue;

	public Variablevalues() {
	}

	public Variablevalues(int variableValuesId) {
		this.variableValuesId = variableValuesId;
	}

	public Variablevalues(int variableValuesId,
			Testsuitevariables testsuitevariables, String variableValue) {
		this.variableValuesId = variableValuesId;
		this.testsuitevariables = testsuitevariables;
		this.variableValue = variableValue;
	}

	public int getVariableValuesId() {
		return this.variableValuesId;
	}

	public void setVariableValuesId(int variableValuesId) {
		this.variableValuesId = variableValuesId;
	}

	public Testsuitevariables getTestsuitevariables() {
		return this.testsuitevariables;
	}

	public void setTestsuitevariables(Testsuitevariables testsuitevariables) {
		this.testsuitevariables = testsuitevariables;
	}

	public String getVariableValue() {
		return this.variableValue;
	}

	public void setVariableValue(String variableValue) {
		this.variableValue = variableValue;
	}

	@Override
	public void AssignTo(IDataTable table) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String printString() {
		String str=null;

		str="Variable Values Id: "+getVariableValuesId()+"\n";
		str+="Testsuitevariables ID:"+ testsuitevariables.getTestSuiteVariableId()+"\n";
		str+="Variable Value: "+getVariableValue()+"\n"; 
		
		Log.Debug("VariableValues:printString : + " + str);
		return str;
	}

}
